language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t matadorvirtuoz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true matadorvirtuoz/docker-react npm run test